author: LPkkjHD
authors: [stefan01, bigibas123]
name: ${project.artifactId}
version: ${project.version}
website: http://freemine.de/
main: de.freemine.permissioneffects.Main
commands:
  PermissionEffects:
    description: "The main command of the ${project.artifactId} plugin"
    permission-message: "§cYou don't have permission §pe.admin §cto use this command"
    usage: "Usage: /<command> [reload/list]"
    aliases: [pe,permissioneffects]
    permission: pe.admin
  ToggleEffects:
    description: "Allows you to toggle the effects that are applied to you"
    permission-message: "§cYou don't have permission §pe.admin §cto use this command"
    usage: "Usage: /<command> <toggle/enable/disable> <effect> [player]"
    aliases: [te,toggle,togglee,teffects,toggleeffects]
    permission: pe.toggle
permissions:
  pe.admin:
    description: "Allows you to use the command /pe"
    default: op
  pe.toggle:
    description: "Allows you to use the command /te"
    default: true
